sudo: false
language: ruby
cache: bundler

rvm:
  - 2.3.1
  - 2.5.1

gemfile:
  - gemfiles/rails-5.1.rb
  - gemfiles/rails-5.2.rb
  - gemfiles/rails-6.0.rb

before_install:
  - gem update --system
  - gem update bundler

matrix:
  exclude:
    # rails 6 will not support ruby < 2.4.1
    - rvm: 2.3.1
      gemfile: gemfiles/rails-6.0.rb
